config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :propositions #index #show #new/create #edit/update #delete
  resources :domains, only: [:index, :read, :update]
  resources :keywords, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root to: 'domains#index'
  get '/search' => 'keyword#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
  # belongs_to :proposition
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  # belongs_to :proposition
end

app/models/proposition.rb
class Proposition < ApplicationRecord
  # has_many :keywords
  # has_many :domains
  # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  def index
    @domains = Domain.all
  end

  def show
    @domain = Domain.find(domain_params)
  end

  def destroy
    @domain = Domain.find(domains_params)
    @domain.destroy
    redirect_to proposition_domains
  end

  private

  def domain_params
    params.require(:domain).permit(:authority_score, :age, :link)
  end


end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def index
    @keywords = Keyword.all
  end

  def show
    @keyword = Keyword.find(params[:id])
  end

  def new
    @keyword = Keyword.new
  end

  def create
    @keyword = Keyword.new(keyword_params)
    @keyword.save
  end

  def edit
    @keyword = Keyword.find(params[:id])
  end

  def update
    @keyword = Keyword.find(params[:id])
    @keyword.update(keyword_params)
  end

  private

  def keyword_params
    params.require(:keyword).permit(:name, :date, :current_rank, :initial_rank, :previous_week_rank)
  end

def rankwatch
  url = URI("https://apiv2.rankwatch.com//project/detail/json/p_id/c581d4904d184a170420d904bc85791c/s_id/2.00426/")

  https = Net::HTTP.new(url.host, url.port);
  https.use_ssl = true

  request = Net::HTTP::Get.new(url)
  request["Authorization"] = "Basic cnctdjItMzg4NjktMjE5MTM6NmFiRHFUNzZSY1NI"

  response = https.request(request)
  puts response.read_body
end
  helper_method :rankwatch

  def find_country(name)
    request_api(
      "https://restcountries-v1.p.rapidapi.com/name/#{URI.encode(name)}"
    )
  end

end

app/controllers/propositions_controller.rb
class PropositionsController < ApplicationController

  def index
    @propositions = Proposition.all
  end

  def show
    @proposition = Proposition.find(params[:id])
  end

  def new
    @proposition = Proposition.new
  end

  def create
    @proposition = Proposition.new(proposition_params)
    @proposition.save
  end

  def edit
    @proposition = Proposition.find(params[:id])
  end

  def update
    @proposition = Proposition.find(params[:id])
    @proposition.update(proposition_params)
  end

  def destroy
    @proposition = Proposition.find(params[:id])
    @proposition.destroy
    redirect_to propositions_path
  end

  private

  def proposition_params
    params.require(:proposition).permit(:name, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/keywords_helper.rb
require "uri"
require "net/http"

module KeywordsHelper

  def rankwatch
    url = URI("https://apiv2.rankwatch.com//project/detail/json/p_id/c581d4904d184a170420d904bc85791c/s_id/2.00426/")

    https = Net::HTTP.new(url.host, url.port);
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["Authorization"] = "Basic cnctdjItMzg4NjktMjE5MTM6NmFiRHFUNzZSY1NI"

    response = https.request(request)
    puts response.read_body

  end

end

app/helpers/propositions_helper.rb
module PropositionsHelper
end

app/views/domains/destroy.html.erb
<h1>Domains#destroy</h1>
<p>Find me in app/views/domains/destroy.html.erb</p>

app/views/domains/index.html.erb
<div class="banner" style="">
  <div class="container">
    <div class="banner-flex">
      <div>
        <br>
        <h1>Home Propositions <strong>Dashboard</strong></h1>
        <p>Digital Progress and Metrics for Nationwide Building Society</p>
        <a class="btn btn-flat" href="https://twitter.com/LLLifeguard">Take a look at us on Social Media</a>
      </div>
      <div>
        <%= image_tag "mountain.png", width:"250px" %>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card-category" style="">
          <div class="card-contents">
            <%= image_tag "house.png", width:"50px" %>
            <p>Landlord Lifeguard</p>
            <%= link_to "View Keywords", keywords_path, class: "btn btn-dark" %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card-category" style="">
          <div class="card-contents">
            <%= image_tag "check.png", width:"50px" %>
            <p>Landlord Finance</p>
            <a class="btn btn-dark" href="#">View Keywords</a>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card-category" style="">
          <div class="card-contents">
            <%= image_tag "tools.png", width:"50px" %>
            <p>Tenant Find</p>
            <a class="btn btn-dark" href="#">View Keywords</a>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card-category" style="">
          <div class="card-contents">
            <%= image_tag "house.png", width:"50px" %>
            <p>MyHatch</p>
            <a class="btn btn-dark" href="#">View Keywords</a>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/domains/show.html.erb
<h1>Domains#show</h1>
<p>Find me in app/views/domains/show.html.erb</p>

app/views/keywords/index.html.erb
<div class="container">
  <h1>Landlord Lifeguard</h1>
    <div>
      <p>Page 1 for branded search consists of:</p>
      <%= Time.now %>
      <br>
        <ul id="keywords"></ul>
    </div>
</div>

app/views/keywords/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :country, 'Search for a country '%>
            <%= text_field_tag :country, nil, placeholder: 'Eg. Germany', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/keywords/search.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>Country info</h4>
      <dl>
        <dt>Country</dt>
        <dd><%= @country['name'] %></dd>
        <dt>Capital</dt>
        <dd><%= @country['capital'] %></dd>
        <dt>Currency</dt>
        <dd><%= @country['currencies'].join(', ') %></dd>
        <dt>Timezone(s)</dt>
        <dd><%= @country['timezones'].join(', ') %></dd>
      </dl>
    </div>
    <div class="col-lg-6">
      <h4>Weather Info</h4>
      <dl>
        <% @weather['list'].each do |weather| %>
          <dt><%= weather['dt_txt'] %></dt>
          <dd>
            <strong>Min</strong> <%= to_fahrenheit weather['main']['temp_min'] %>
            <strong>Max</strong> <%= to_fahrenheit weather['main']['temp_max'] %>
          </dd>
        <% end %>
      </dl>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HomePropositionsDigital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/propositions/index.html.erb
<div class="banner" style="">
  <div class="container">
    <div class="banner-flex">
      <div>
        <br>
        <h1>Home Propositions <strong>Dashboard</strong></h1>
        <p>Digital Progress and Metrics for Nationwide Building Society</p>
        <a class="btn btn-flat" href="#">View Keywords</a>
      </div>
      <div>
        <%= image_tag "mountain.png", width:"250px" %>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card-category" style="">
          <div class="card-contents">
            <%= image_tag "house.png", width:"50px" %>
            <p>Landlord Lifeguard</p>
            <a class="btn btn-dark" href="#">View Keywords</a>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card-category" style="">
          <div class="card-contents">
            <%= image_tag "check.png", width:"50px" %>
            <p>Landlord Finance</p>
            <a class="btn btn-dark" href="#">View Keywords</a>
          </div>
        </div>
      </div>
    </div>
</div>


<div class="container">
  <h1>This will be a list of all our keywords</h1>

<div>
  <p>Our branded keyword search results are:</p>
    <ul id="keywords"></ul>
</div>

</div>

app/views/propositions/new.html.erb
<h1>This is where you can create a new proposition to track for our team</h1>

<p>Coming soon :)</p>

app/views/propositions/show.html.erb
<h1>This propositions page is for:</h1>

<%= @proposition.name %>
<br>
<%= @proposition.status %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to image_tag("logo.png"), root_path %>
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "Rankings", class: "dropdown-item" %>
            <%= link_to "Another action", "Domain", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>